# Generated by Django 4.1.2 on 2024-02-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_message_chat_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerconnections',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='consumerconnections',
            name='user',
        ),
        migrations.DeleteModel(
            name='Connections',
        ),
        migrations.DeleteModel(
            name='ConsumerConnections',
        ),
    ]
